import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import CodeBlock from './CodeBlock';

const markdownComponents = {
  code({ className, children, inline, ...props }) {
    const match = /language-(\w+)/.exec(className || '');
    const lang = match ? match[1] : undefined;
    const code = String(children).replace(/\n$/, '');
    return <CodeBlock code={code} language={lang} inline={inline} highlight={false} />;
  },
};

/**
 * A single log line — supports plain text, SVG icons, markdown,
 * and structured tool-name rendering.
 *
 * Security: We NEVER use dangerouslySetInnerHTML for LLM-generated content.
 * The only exception is app-generated SVG icons (emoji replacement) which
 * are validated before rendering.
 */

// Simple HTML-escape for plain-text content
function escapeHtml(text) {
  if (!text) return '';
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Validate that an SVG string looks like an emoji icon from our backend
// (viewBox="0 0 24 24", no script/event-handler attributes)
function isSafeEmojiSvg(svg) {
  if (!svg || typeof svg !== 'string') return false;
  if (!/^<svg\s/.test(svg.trim()) || !/<\/svg>\s*$/.test(svg.trim())) return false;
  // Must have viewBox (our emoji SVGs use 0 0 24 24)
  if (!/\bviewBox\s*=\s*["']0\s+0\s+(?:20\s+20|24\s+24)["']/.test(svg)) return false;
  // Reject dangerous constructs
  if (/<script\b/i.test(svg)) return false;
  if (/\bon\w+\s*=/i.test(svg)) return false;
  if (/javascript\s*:/i.test(svg)) return false;
  return true;
}

// Global regex to find safe emoji SVGs anywhere in text
const _SVG_GLOBAL_RE = /<svg\s[^>]*>.*?<\/svg>/gs;

// Split text into alternating text/SVG segments.
// Returns an array of {type: 'svg'|'text', value: string} segments.
// SVGs that fail isSafeEmojiSvg are left as raw text.
export function splitTextAndSvgs(text) {
  if (!text || typeof text !== 'string') return [{ type: 'text', value: text || '' }];
  const parts = [];
  let lastIdx = 0;
  let match;
  // Reset lastIndex in case the regex has state
  _SVG_GLOBAL_RE.lastIndex = 0;
  while ((match = _SVG_GLOBAL_RE.exec(text)) !== null) {
    // Text before this SVG
    if (match.index > lastIdx) {
      parts.push({ type: 'text', value: text.slice(lastIdx, match.index) });
    }
    const svg = match[0];
    if (isSafeEmojiSvg(svg)) {
      parts.push({ type: 'svg', value: svg });
    } else {
      // Not our SVG — leave as raw text
      parts.push({ type: 'text', value: svg });
    }
    lastIdx = match.index + svg.length;
  }
  // Trailing text
  if (lastIdx < text.length) {
    parts.push({ type: 'text', value: text.slice(lastIdx) });
  }
  return parts.length > 0 ? parts : [{ type: 'text', value: text }];
}

// Extract an SVG icon from the start of a text string (legacy helper).
// Returns { svgIcon, text } if found, or null.
export function extractSvgFromText(text) {
  if (!text || typeof text !== 'string') return null;
  const m = text.match(/^(<svg\b[^>]*>.*?<\/svg>)\s*(.*)$/s);
  if (!m) return null;
  const svg = m[1];
  const rest = m[2] || '';
  if (!isSafeEmojiSvg(svg)) return null;
  return { svgIcon: svg, text: rest };
}


export default function LogLine({ line }) {
  // React component — render directly
  if (line.component) {
    return <div className={line.cls || ''}>{line.component}</div>;
  }

  // Structured tool name (replaces the old dangerouslySetInnerHTML for html)
  if (line.toolName) {
    return (
      <div className={line.cls || ''}>
        <span className="accent">{line.toolName}</span>
        {line.toolArgs && <span className="dim">{line.toolArgs}</span>}
      </div>
    );
  }

  // SVG icon (only used for app-generated emoji icons — validated for safety)
  if (line.svgIcon && isSafeEmojiSvg(line.svgIcon)) {
    return (
      <div className={line.cls || ''}>
        <span
          className="emoji-icon"
          dangerouslySetInnerHTML={{ __html: line.svgIcon }}
        />
        <span>{escapeHtml(line.text)}</span>
      </div>
    );
  }

  // Markdown rendering (NO allowDangerousHtml — LLM output is sanitised).
  // SVGs generated by the backend (emoji→icon replacement) are extracted
  // from the text and rendered as real SVG DOM nodes so they appear as
  // icons rather than raw HTML source.
  if (line.markdown) {
    const segments = splitTextAndSvgs(line.text);
    return (
      <div className={`md-line ${line.cls || ''}`} style={{ whiteSpace: 'normal' }}>
        {segments.map((seg, i) => {
          if (seg.type === 'svg') {
            return (
              <span
                key={`svg-${i}`}
                className="emoji-icon"
                dangerouslySetInnerHTML={{ __html: seg.value }}
              />
            );
          }
          // Empty text segment — skip to avoid ReactMarkdown error on empty string
          if (!seg.value.trim()) return null;
          return (
            <ReactMarkdown
              key={`md-${i}`}
              remarkPlugins={[remarkGfm]}
              components={{
                p: ({ children }) => <span>{children}</span>,
                ...markdownComponents,
              }}
            >
              {seg.value}
            </ReactMarkdown>
          );
        })}
      </div>
    );
  }

  // Plain text — split into text/SVG segments for inline icon rendering
  const segments = splitTextAndSvgs(line.text);
  if (segments.length > 1 || (segments.length === 1 && segments[0].type === 'svg')) {
    return (
      <div className={line.cls || ''}>
        {segments.map((seg, i) => {
          if (seg.type === 'svg') {
            return (
              <span
                key={`svg-${i}`}
                className="emoji-icon"
                dangerouslySetInnerHTML={{ __html: seg.value }}
              />
            );
          }
          return <span key={`txt-${i}`}>{escapeHtml(seg.value)}</span>;
        })}
      </div>
    );
  }

  // Plain text — HTML-escaped
  return <div className={line.cls || ''}>{escapeHtml(line.text)}</div>;
}
