#!/usr/bin/env python3
"""
schema.py -- TOOLS definitions sent to the LLM

Pi-style: concise descriptions, consistent naming, no redundant tools.
"""
from __future__ import annotations

TOOLS = [
    # ── File I/O ───────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "read_file", "description": "Read a file. Use from_line/to_line for ranges, or just path for entire file. Lines are 1-indexed, inclusive.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Path to file"}, "from_line": {"type": "number", "description": "1-based start line (inclusive)"}, "to_line": {"type": "number", "description": "1-based end line (inclusive)"}}, "required": ["path"]}}},
    {"type": "function", "function": {"name": "write_file", "description": "Write content to a file. Creates file and parent dirs automatically.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Path to file"}, "content": {"type": "string", "description": "Content to write"}}, "required": ["path", "content"]}}},
    {"type": "function", "function": {"name": "edit_file", "description": "Edit a file by exact text replacement. Each edit has oldText (text to find) and newText (replacement). oldText must be unique in the file. Merge nearby changes into one edit.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Path to file"}, "edits": {"type": "array", "items": {"type": "object", "properties": {"oldText": {"type": "string", "description": "Exact text to replace"}, "newText": {"type": "string", "description": "Replacement text"}, "edit_type": {"type": "string", "description": "'replace' (default), 'insert_after', or 'insert_before'"}}, "required": ["oldText", "newText"]}, "description": "List of edits"}}, "required": ["path", "edits"]}}},
    {"type": "function", "function": {"name": "list_directory", "description": "List contents of a directory.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Directory path"}}, "required": ["path"]}}},
    {"type": "function", "function": {"name": "file_info", "description": "Get metadata about a file or directory.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Path to inspect"}}, "required": ["path"]}}},

    # ── Shell ──────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "run_shell", "description": "Execute a shell command. Output truncated at 2000 lines.", "parameters": {"type": "object", "properties": {"command": {"type": "string", "description": "Shell command"}, "background": {"type": "boolean", "description": "Run in background, use task_status to check"}, "timeout": {"type": "integer", "description": "Max seconds (default 60)"}}, "required": ["command"]}}},
    {"type": "function", "function": {"name": "task_status", "description": "Check a background task by its ID.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID from run_shell background=True"}}, "required": ["task_id"]}}},

    # ── Search ─────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "search_files", "description": "Search for a text pattern in files. Returns matching lines with file:line.", "parameters": {"type": "object", "properties": {"pattern": {"type": "string", "description": "Text or regex to find"}, "path": {"type": "string", "description": "Directory to search (default workspace)"}, "file_path": {"type": "string", "description": "Restrict to single file"}, "regex": {"type": "boolean", "description": "Treat pattern as regex"}, "ignore_case": {"type": "boolean", "description": "Case insensitive"}}, "required": ["pattern"]}}},
    {"type": "function", "function": {"name": "find_symbol", "description": "Find where a symbol is defined. Returns file + line for each match.", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Symbol name (e.g. 'ToolResult')"}}, "required": ["name"]}}},
    {"type": "function", "function": {"name": "find_usages", "description": "Find all references to a symbol across the workspace.", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Symbol name"}}, "required": ["name"]}}},
    {"type": "function", "function": {"name": "semantic_search", "description": "Search code by meaning using embeddings. For when you don't know the exact name.", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Natural language query"}, "path": {"type": "string", "description": "Directory to search"}}, "required": ["query"]}}},
    {"type": "function", "function": {"name": "web_search", "description": "Search the web. Returns titles, URLs, and excerpts.", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}, "num_results": {"type": "integer", "description": "Results count (default 5)"}}, "required": ["query"]}}},
    {"type": "function", "function": {"name": "session_search", "description": "Search past session messages. Use for 'we fixed this before' queries.", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search terms"}, "limit": {"type": "integer", "description": "Max results (default 10)"}}, "required": ["query"]}}},

    # ── Code Intelligence ─────────────────────────────────────────────
    {"type": "function", "function": {"name": "get_file_skeleton", "description": "Get structural outline of files (classes, functions, methods) without implementation.", "parameters": {"type": "object", "properties": {"paths": {"type": "array", "items": {"type": "string"}, "description": "File paths"}}, "required": ["paths"]}}},
    {"type": "function", "function": {"name": "get_function", "description": "Extract full implementation of specific functions/methods from files.", "parameters": {"type": "object", "properties": {"paths": {"type": "array", "items": {"type": "string"}, "description": "File paths"}, "function_names": {"type": "array", "items": {"type": "string"}, "description": "Function names, supports Class.method"}}, "required": ["paths", "function_names"]}}},
    {"type": "function", "function": {"name": "replace_symbol", "description": "Replace a symbol (function/method/class) using AST-precise byte ranges.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "File path"}, "symbol": {"type": "string", "description": "Dot-separated symbol path"}, "text": {"type": "string", "description": "Complete replacement code"}}, "required": ["path", "symbol", "text"]}}},
    {"type": "function", "function": {"name": "get_symbol_range", "description": "Get byte range of a symbol for use before replace_symbol.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "File path"}, "symbol": {"type": "string", "description": "Dot-separated symbol path"}}, "required": ["path", "symbol"]}}},

    # ── Testing ───────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "run_tests", "description": "Run tests. If path given runs those tests only.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Test file or directory"}, "background": {"type": "boolean", "description": "Run in background"}}, "required": []}}},
    {"type": "function", "function": {"name": "verify", "description": "Lint + test files modified this session.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "diagnose_failures", "description": "Read last test output and extract failure details.", "parameters": {"type": "object", "properties": {}, "required": []}}},

    # ── Git ───────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "git_status", "description": "Show git status --short.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "git_diff", "description": "Show git diff. staged=true for staged changes.", "parameters": {"type": "object", "properties": {"staged": {"type": "boolean", "description": "Show staged diff"}, "path": {"type": "string", "description": "Restrict to file"}}, "required": []}}},
    {"type": "function", "function": {"name": "git_log", "description": "Show recent commits (oneline).", "parameters": {"type": "object", "properties": {"n": {"type": "integer", "description": "Number of commits (default 10)"}}, "required": []}}},
    {"type": "function", "function": {"name": "git_add", "description": "Stage files. paths='all' for everything.", "parameters": {"type": "object", "properties": {"paths": {"type": "string", "description": "'all' or file path"}}, "required": ["paths"]}}},
    {"type": "function", "function": {"name": "git_commit", "description": "Commit staged changes.", "parameters": {"type": "object", "properties": {"message": {"type": "string", "description": "Commit message"}}, "required": ["message"]}}},

    # ── Planning / Tracking ───────────────────────────────────────────
    {"type": "function", "function": {"name": "write_scratchpad", "description": "Write to your persistent scratchpad (markdown). Survives across turns.", "parameters": {"type": "object", "properties": {"content": {"type": "string", "description": "Scratchpad content"}}, "required": ["content"]}}},
    {"type": "function", "function": {"name": "plan", "description": "Declare a task plan with ordered steps.", "parameters": {"type": "object", "properties": {"steps": {"type": "array", "items": {"type": "string"}, "description": "Ordered step descriptions"}}, "required": ["steps"]}}},
    {"type": "function", "function": {"name": "plan_status", "description": "View plan progress or mark a step complete (1-indexed).", "parameters": {"type": "object", "properties": {"step": {"type": "integer", "description": "Step to mark complete (1-indexed)"}}, "required": []}}},
    {"type": "function", "function": {"name": "todo_write", "description": "Create or update a todo item.", "parameters": {"type": "object", "properties": {"content": {"type": "string", "description": "Todo text. Empty to delete."}, "id": {"type": "string", "description": "Existing todo id to update"}, "status": {"type": "string", "description": "'pending' or 'done'"}}, "required": ["content"]}}},
    {"type": "function", "function": {"name": "todo_read", "description": "Read your current todo list.", "parameters": {"type": "object", "properties": {"id": {"type": "string", "description": "Filter by id"}, "status": {"type": "string", "description": "Filter by 'pending' or 'done'"}}, "required": []}}},

    # ── Memory ────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "remember", "description": "Save a learning for future sessions.", "parameters": {"type": "object", "properties": {"topic": {"type": "string", "description": "Short label"}, "detail": {"type": "string", "description": "What to remember"}}, "required": ["topic", "detail"]}}},
    {"type": "function", "function": {"name": "memory_core", "description": "Manage persistent core memory. action: 'read', 'add', 'replace', 'remove'.", "parameters": {"type": "object", "properties": {"action": {"type": "string", "description": "'read', 'add', 'replace', or 'remove'"}, "content": {"type": "string", "description": "Content for add/replace"}, "line": {"type": "integer", "description": "Line number to remove (1-indexed)"}}, "required": ["action"]}}},
    {"type": "function", "function": {"name": "session_stats", "description": "Show session: turns, tokens, cache hit rate, cost.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "recall_turn", "description": "Recall what happened on a specific turn.", "parameters": {"type": "object", "properties": {"turn": {"type": "integer", "description": "Turn number (1-indexed)"}}, "required": ["turn"]}}},
    {"type": "function", "function": {"name": "write_session_handoff", "description": "Write HANDOFF.md for next-session continuity.", "parameters": {"type": "object", "properties": {"pending": {"type": "string", "description": "Unfinished work"}, "notes": {"type": "string", "description": "Extra context"}}, "required": []}}},
    {"type": "function", "function": {"name": "restore_file", "description": "Restore a file from session backup.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "File path"}}, "required": ["path"]}}},

    # ── Sub-Agents ────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "spawn_agent", "description": "Spawn a sub-agent to work in background. Use 'task' for single, 'tasks' for parallel.", "parameters": {"type": "object", "properties": {"task": {"type": "string", "description": "Task description"}, "tasks": {"type": "array", "items": {"type": "string"}, "description": "Multiple tasks"}, "shared_context": {"type": "string", "description": "Shared info for all agents"}, "max_turns": {"type": "integer", "description": "Turns per agent (default 15)"}}, "required": []}}},
    {"type": "function", "function": {"name": "agent_status", "description": "Check sub-agent status: running, completed, or not_found.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}}, "required": ["task_id"]}}},
    {"type": "function", "function": {"name": "collect_agent", "description": "Block until a sub-agent completes, return its result.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}}, "required": ["task_id"]}}},
    {"type": "function", "function": {"name": "collect_any", "description": "Collect the first sub-agent that finishes.", "parameters": {"type": "object", "properties": {"task_ids": {"type": "array", "items": {"type": "string"}, "description": "Task IDs to check"}}, "required": []}}},
    {"type": "function", "function": {"name": "agent_extend", "description": "Give a sub-agent more turns.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}, "additional": {"type": "integer", "description": "Extra turns (default 10)"}}, "required": ["task_id"]}}},
    {"type": "function", "function": {"name": "agent_cancel", "description": "Cancel a running sub-agent.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Task ID"}}, "required": ["task_id"]}}},
    {"type": "function", "function": {"name": "agent_message", "description": "Broadcast a message to parent and sibling agents.", "parameters": {"type": "object", "properties": {"text": {"type": "string", "description": "Message text"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "agent_read", "description": "Read broadcast messages from other agents.", "parameters": {"type": "object", "properties": {"since": {"type": "integer", "description": "Only return messages with index >= this"}}, "required": []}}},
    {"type": "function", "function": {"name": "agent_inbox", "description": "Read typed inbox messages for an agent.", "parameters": {"type": "object", "properties": {"task_id": {"type": "string", "description": "Agent's task ID"}, "since": {"type": "integer", "description": "Only messages with index >= this"}}, "required": []}}},
    {"type": "function", "function": {"name": "wait_for_agent", "description": "Block until any specified agent completes.", "parameters": {"type": "object", "properties": {"task_ids": {"type": "array", "items": {"type": "string"}, "description": "Task IDs to wait for"}, "timeout": {"type": "integer", "description": "Max seconds (default 120)"}}, "required": ["task_ids"]}}},
    {"type": "function", "function": {"name": "fan_out", "description": "Spawn multiple agents from a list of descriptions.", "parameters": {"type": "object", "properties": {"descriptions": {"type": "array", "items": {"type": "string"}, "description": "Task descriptions"}, "shared_context": {"type": "string", "description": "Shared context"}}, "required": ["descriptions"]}}},
    {"type": "function", "function": {"name": "fan_in", "description": "Collect results from a set of sub-agents.", "parameters": {"type": "object", "properties": {"task_ids": {"type": "array", "items": {"type": "string"}, "description": "Task IDs"}, "timeout": {"type": "integer", "description": "Max seconds (default 60)"}}, "required": ["task_ids"]}}},
    {"type": "function", "function": {"name": "pipeline", "description": "Execute tasks sequentially, each waiting for the previous.", "parameters": {"type": "object", "properties": {"stages": {"type": "array", "items": {"type": "string"}, "description": "Task descriptions in order"}}, "required": ["stages"]}}},
    {"type": "function", "function": {"name": "barrier", "description": "Block until all specified agents complete.", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Barrier name"}, "task_ids": {"type": "array", "items": {"type": "string"}, "description": "Task IDs to wait for"}}, "required": ["name", "task_ids"]}}},
    {"type": "function", "function": {"name": "scatter_gather", "description": "Apply template across items in parallel, collect results.", "parameters": {"type": "object", "properties": {"template": {"type": "string", "description": "Task template with {item} placeholder"}, "items": {"type": "array", "items": {"type": "string"}, "description": "Items to scatter"}}, "required": ["template", "items"]}}},
    {"type": "function", "function": {"name": "audit_parallel", "description": "Fan-out code audit across defect classes in parallel.", "parameters": {"type": "object", "properties": {"defect_classes": {"type": "array", "items": {"type": "string"}, "description": "Defect categories"}, "workspace_scope": {"type": "string", "description": "Limit to subdirectory"}}, "required": ["defect_classes"]}}},

    # ── LSP ───────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "lsp_definition", "description": "Go to definition via LSP.", "parameters": {"type": "object", "properties": {"file_path": {"type": "string", "description": "File path"}, "line": {"type": "integer", "description": "0-indexed line"}, "character": {"type": "integer", "description": "0-indexed character"}}, "required": ["file_path", "line", "character"]}}},
    {"type": "function", "function": {"name": "lsp_references", "description": "Find all references via LSP.", "parameters": {"type": "object", "properties": {"file_path": {"type": "string", "description": "File path"}, "line": {"type": "integer", "description": "0-indexed line"}, "character": {"type": "integer", "description": "0-indexed character"}}, "required": ["file_path", "line", "character"]}}},
    {"type": "function", "function": {"name": "lsp_hover", "description": "Get hover info (type, docs) via LSP.", "parameters": {"type": "object", "properties": {"file_path": {"type": "string", "description": "File path"}, "line": {"type": "integer", "description": "0-indexed line"}, "character": {"type": "integer", "description": "0-indexed character"}}, "required": ["file_path", "line", "character"]}}},
    {"type": "function", "function": {"name": "lsp_diagnostics", "description": "Get errors/warnings for a file via LSP.", "parameters": {"type": "object", "properties": {"file_path": {"type": "string", "description": "File path"}}, "required": ["file_path"]}}},

    # ── Browser ───────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "browser_navigate", "description": "Navigate headless browser to URL.", "parameters": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to navigate to"}}, "required": ["url"]}}},
    {"type": "function", "function": {"name": "browser_snapshot", "description": "Get accessibility tree of current page.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "browser_click", "description": "Click an element by role and name.", "parameters": {"type": "object", "properties": {"role": {"type": "string", "description": "ARIA role (button, link, textbox)"}, "name": {"type": "string", "description": "Accessible name"}}, "required": ["role", "name"]}}},
    {"type": "function", "function": {"name": "browser_type", "description": "Type text into an input element.", "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Accessible name"}, "text": {"type": "string", "description": "Text to type"}, "role": {"type": "string", "description": "Role (default textbox)"}}, "required": ["name", "text"]}}},
    {"type": "function", "function": {"name": "browser_screenshot", "description": "Capture full-page PNG screenshot.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Save path (default browser_screenshot.png)"}}, "required": []}}},

    # ── Desktop ───────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "desktop_snapshot", "description": "Get accessibility tree of frontmost desktop window.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "desktop_click", "description": "Click native desktop element by role and name.", "parameters": {"type": "object", "properties": {"role": {"type": "string", "description": "Element role"}, "name": {"type": "string", "description": "Accessible name"}}, "required": ["role", "name"]}}},
    {"type": "function", "function": {"name": "desktop_type", "description": "Type text into focused field.", "parameters": {"type": "object", "properties": {"text": {"type": "string", "description": "Text to type"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "desktop_screenshot", "description": "Capture desktop PNG screenshot.", "parameters": {"type": "object", "properties": {}, "required": []}}},

    # ── Misc ──────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "fetch_url", "description": "Fetch text content of a URL.", "parameters": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to fetch"}}, "required": ["url"]}}},
    {"type": "function", "function": {"name": "read_image", "description": "Read an image file, return text description via GPT-4o.", "parameters": {"type": "object", "properties": {"path": {"type": "string", "description": "Image path"}, "prompt": {"type": "string", "description": "Question about image"}}, "required": ["path"]}}},
    {"type": "function", "function": {"name": "init", "description": "Auto-generate .mini_agent.rules and .mini_agent.toml for workspace.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "condense", "description": "Compact conversation to free context space.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "discord_search", "description": "Search Discord message history.", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "Search terms"}}, "required": ["query"]}}},
]
